### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by hengsoheak** [DecisiveMocha/ghostpdl#1]
I'm trying to install **_ghostpdl-9-2.21_** on MACOS Sierra version:10.12.4 then I got below errors.

`./obj/aux/echogs -w ./obj/ldt.tr -n - gcc -L/usr/X11/lib -o ./bin/gs ./obj/aux/echogs -a ./obj/ldt.tr -n -s ./obj/gsromfs1.o ./obj/gs.o -s cat ./obj/gsld.tr >> ./obj/ldt.tr ./obj/aux/echogs -a ./obj/ldt.tr -s - -lm -ldl -liconv -L/opt/local/lib -lfontconfig -lfreetype -lpthread -lm if [ x != x ]; then LD_RUN_PATH=; export LD_RUN_PATH; fi; \ XCFLAGS= XINCLUDE= XLDFLAGS= XLIBDIRS= XLIBS= \ PSI_FEATURE_DEVS= FEATURE_DEVS= DEVICE_DEVS= DEVICE_DEVS1= DEVICE_DEVS2= DEVICE_DEVS3= \ DEVICE_DEVS4= DEVICE_DEVS5= DEVICE_DEVS6= DEVICE_DEVS7= DEVICE_DEVS8= \ DEVICE_DEVS9= DEVICE_DEVS10= DEVICE_DEVS11= DEVICE_DEVS12= \ DEVICE_DEVS13= DEVICE_DEVS14= DEVICE_DEVS15= DEVICE_DEVS16= \ DEVICE_DEVS17= DEVICE_DEVS18= DEVICE_DEVS19= DEVICE_DEVS20= \ DEVICE_DEVS_EXTRA= \ /bin/sh <./obj/ldt.tr Undefined symbols for architecture x86_64: "_iconv", referenced from: _opvp_to_utf8 in gdevopvp.o "_iconv_close", referenced from: _opvp_to_utf8 in gdevopvp.o "_iconv_open", referenced from: _opvp_to_utf8 in gdevopvp.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [bin/gs] Error 1`

**Comment by DecisiveMocha** [comment]
I don't own or maintain Ghostscript. I forked it to add a driver for a printer I use. Unfortunately, I don't really know enough to help you build it on MacOS.

**Comment by hengsoheak** [comment]
OK thanks now I'm testing in ubintu16
